name: Match vs Previous Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fastchess-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for previous commit

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build current Copperfish
      - name: Build current Copperfish
        run: cargo build --release
      - name: Copy current binary
        run: cp target/release/copperfish copperfish-current

      # Checkout previous commit and build
      - name: Checkout previous commit
        run: git checkout HEAD~1
      - name: Build previous Copperfish
        run: cargo build --release
      - name: Copy previous binary
        run: cp target/release/copperfish copperfish-prev

      # Download and install fastchess
      - name: Install fastchess
        run: |
          wget -q https://github.com/Disservin/fastchess/releases/download/v1.6.0-alpha/fastchess-linux-x86-64.tar
          tar -xf fastchess-linux-x86-64.tar
          chmod +x fastchess-linux-x86-64/fastchess
          cp fastchess-linux-x86-64/fastchess .
          ls -al

      # Download opening book
      - name: Download opening book
        run: |
          wget -q https://github.com/official-stockfish/books/raw/refs/heads/master/8moves_v3.pgn.zip
          unzip 8moves_v3.pgn.zip

      # Run a fastchess match with PGN output
      - name: Run match Copperfish HEAD vs previous
        run: |
          ./fastchess \
            -engine cmd=./copperfish-current name=Current \
            -engine cmd=./copperfish-prev name=Previous \
            -each tc=0+3 \
            -openings file=8moves_v3.pgn format=pgn order=random \
            -srand $RANDOM \
            -rounds 60 \
            -concurrency 2 \
            -log file=fastchess.log \
            -pgnout match.pgn
          cat fastchess.log

      # Upload PGN as artifact
      - name: Upload PGN artifact
        uses: actions/upload-artifact@v4
        with:
          name: copperfish-fastchess-pgn
          path: match.pgn
